[package]
name = "from-env"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
from-env-derive = { git = "https://github.com/wangjun861205/from-env-derive-rs" }
